name: mcquenji_desktop
description: "Provides modules for developing desktop applications."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_modular: ^6.3.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  logging: ^1.2.0
  mcquenji_core:
    git:
      url: https://github.com/mcquenji/mcquenji_core.git
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
